- name: Setup Theos
        run: |
          # Theosの本体を取得
          sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
          
          # SDKを取得
          curl -LO https://github.com/theos/sdks/archive/master.zip
          TMP=$(mktemp -d)
          unzip master.zip -d $TMP
          sudo mv $TMP/sdks-master/*.sdk /opt/theos/sdks
          rm -rf master.zip $TMP
          
          # 【ここを追加！】ldid（署名ツール）をインストール
          brew install ldid
          
          echo "THEOS=/opt/theos" >> $GITHUB_ENV
